name: Release Go Binaries

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: gnostic
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Release
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.22.10.linux-amd64.tar.gz"
          project_path: "./"
          binary_name: gnostic

        

